Add a byte-wide module

diff --git a/scripts/verify b/scripts/verify
--- a/scripts/verify
+++ b/scripts/verify
@@ -17,10 +17,11 @@ cleanup() {
 	rm a.out *.vcd
 }
 
-if ! (verif GPIA_BIT); then
-	echo "FAIL"
-	exit 1
-fi
+for x in GPIA_BIT GPIA_BYTE; do
+	if ! (verif $x); then
+		echo "FAIL"
+		exit 1
+	fi
+done
 
 (cd $BENCH/verilog && cleanup)
-
